#!/usr/bin/env python3

import sys

filename = '0.in' if len(sys.argv) < 2 else sys.argv[1]

values = {}
G = {}

for line in open(filename).readlines():
    tokens = line.rstrip().split(':')
    pre = tokens[0][:-1]
    r = tokens[1][1:].split(' ')
    children = []
    for i in range(0, len(r), 2):
      G[r[i]] = r[i+1]
      children.append(r[i])


    G[pre] = children
    print(pre, children)
    exit(0)

print(G)
